### ISSUE TITLE
When converting pycharm-debug.egg to a wheel an exception is raised

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#129]
Originally reported by: **Omer Katz (Bitbucket: [the_drow](https://bitbucket.org/the_drow), GitHub: Unknown)**

----------------------------------------

Traceback (most recent call last):
  File "/var/www/zconsole.vnv/bin/wheel", line 11, in <module>
    sys.exit(main())
  File "/var/www/zconsole.vnv/local/lib/python2.7/site-packages/wheel/tool/__init__.py", line 358, in main
    args.func(args)
  File "/var/www/zconsole.vnv/local/lib/python2.7/site-packages/wheel/tool/__init__.py", line 329, in convert_f
    convert(args.installers, args.dest_dir, args.verbose)
  File "/var/www/zconsole.vnv/local/lib/python2.7/site-packages/wheel/tool/__init__.py", line 260, in convert
    conv(installer, dest_dir)
  File "/var/www/zconsole.vnv/local/lib/python2.7/site-packages/wheel/egg2wheel.py", line 35, in egg2wheel
    pyver = egg_info['pyver'].replace('.', '')
AttributeError: 'NoneType' object has no attribute 'replace'

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/129

**Comment by agronholm** [comment]
@beamerblvd is this still relevant? 2.5 years have passed.

**Comment by agronholm** [comment]
Yep, feels like this issue is obsolete. Reopen if you disagree.

**Comment by agronholm** [comment]
Reopening because this needs a friendly error message.
