### ISSUE TITLE
wheel crashes with named pipe in directory

### ISSUE THREAD

**Issue by diefans** [pypa/wheel#223]
```
pip wheel --wheel-dir ./wheels .
Processing /home/code/bm/ucs/univention-bm-app
Exception:
Traceback (most recent call last):
  File "/home/olli/.pyenv/versions/3.6.4/envs/bm-ucs/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/home/olli/.pyenv/versions/3.6.4/envs/bm-ucs/lib/python3.6/site-packages/pip/commands/wheel.py", line 199, in run
    if not wb.build():
  File "/home/olli/.pyenv/versions/3.6.4/envs/bm-ucs/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/home/olli/.pyenv/versions/3.6.4/envs/bm-ucs/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/home/olli/.pyenv/versions/3.6.4/envs/bm-ucs/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/home/olli/.pyenv/versions/3.6.4/envs/bm-ucs/lib/python3.6/site-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/home/olli/.pyenv/versions/3.6.4/envs/bm-ucs/lib/python3.6/site-packages/pip/download.py", line 686, in unpack_file_url
    shutil.copytree(link_path, location, symlinks=True)
  File "/home/olli/.pyenv/versions/3.6.4/lib/python3.6/shutil.py", line 359, in copytree
    raise Error(errors)
shutil.Error: [('/home/code/bm/ucs/univention-bm-app/.uwsgi.fifo', '/tmp/pip-xd3ncb3o-build/.uwsgi.fifo', '`/home/code/bm/ucs/univention-bm-app/.uwsgi.fifo` is a named pipe')]
```

**Comment by agronholm** [comment]
You realize that the traceback comes from pip, not wheel? What can wheel do to remedy this?

**Comment by diefans** [comment]
You are right. My naive assumption was, that this must belong to your project... sorry for the noise, I will open a ticket at https://github.com/pypa/pip
