### ISSUE TITLE
bdist_wheel --build BUILD_NUMBER creates two *.dist-info directories

### ISSUE THREAD

**Issue by roee30** [pypa/wheel#263]
**Steps to reproduce**:

From the root of the repository (e.g: this very repository) run:
```
python setup.py bdist_wheel --build-number 123
unzip -l dist/wheel-0.32.1-123-py2.py3-none-any.whl | grep dist
```

**Result**:
```
Archive:  dist/wheel-0.32.1-123-py2.py3-none-any.whl
    14481  2018-10-04 08:38   wheel/bdist_wheel.py
     1125  2018-10-04 08:42   wheel-0.32.1-123.dist-info/LICENSE.txt
     2080  2018-10-04 08:42   wheel-0.32.1-123.dist-info/METADATA
      121  2018-10-04 08:42   wheel-0.32.1-123.dist-info/WHEEL
      108  2018-10-04 08:42   wheel-0.32.1-123.dist-info/entry_points.txt
        6  2018-10-04 08:42   wheel-0.32.1-123.dist-info/top_level.txt
     1468  2018-10-04 08:42   wheel-0.32.1.dist-info/RECORD
```
Notice `RECORD` is in the wrong directory.
Trying to install this wheel:

```
$ pip install dist/*
...
Processing ./dist/wheel-0.32.1-123-py2.py3-none-any.whl
Installing collected packages: wheel
  Found existing installation: wheel 0.30.0
    Uninstalling wheel-0.30.0:
      Successfully uninstalled wheel-0.30.0
  Rolling back uninstall of wheel
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/basecommand.py", line 141, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/commands/install.py", line 347, in run
    use_user_site=options.use_user_site,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/__init__.py", line 49, in install_given_reqs
    **kwargs
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/req_install.py", line 941, in install
    use_user_site=use_user_site, pycompile=pycompile,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/req/req_install.py", line 526, in move_wheel_files
    warn_script_location=warn_script_location,
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/wheel.py", line 324, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/local/lib/python2.7/dist-packages/pip/_internal/wheel.py", line 273, in clobber
    ', '.join(info_dir))
AssertionError: Multiple .dist-info directories: /usr/local/lib/python2.7/dist-packages/wheel-0.32.1.dist-info, /usr/local/lib/python2.7/dist-packages/wheel-0.32.1-123.dist-info
```
**Expected result:**
```
$ unzip -l dist/wheel-0.32.1-123-py2.py3-none-any.whl | grep dist
Archive:  dist/wheel-0.32.1-123-py2.py3-none-any.whl
    14481  2018-10-04 08:38   wheel/bdist_wheel.py
     1125  2018-10-04 08:42   wheel-0.32.1-123.dist-info/LICENSE.txt
     2080  2018-10-04 08:42   wheel-0.32.1-123.dist-info/METADATA
      121  2018-10-04 08:42   wheel-0.32.1-123.dist-info/WHEEL
      108  2018-10-04 08:42   wheel-0.32.1-123.dist-info/entry_points.txt
        6  2018-10-04 08:42   wheel-0.32.1-123.dist-info/top_level.txt
     1468  2018-10-04 08:42   wheel-0.32.1-123.dist-info/RECORD
```

**Comment by agronholm** [comment]
What I'm not sure about is whether the .dist-info directory name should even contain the build number in the first place. PEP 427 makes no mention of this. @dholth what do you say?

**Comment by benoit-pierre** [comment]
The [file contents](https://www.python.org/dev/peps/pep-0427/#file-contents) section uses `{distribution}-{version}.dist-info/` everywhere.

**Comment by dholth** [comment]
My reading of the PEP says the build number does not appear in the dist-info directory name.
The build number feature exists on the basis that every level of packaging needs its own version number. See also RPM epoch numbers.
