### ISSUE TITLE
Regression with ABI3 wheels on 0.33.5

### ISSUE THREAD

**Issue by HexDecimal** [pypa/wheel#305]
These wheels worked with version 0.33.4, but crash on 0.33.5:

On Linux:
```
$ python setup.py build -g develop bdist_wheel --py-limited-api=cp35
...
Traceback (most recent call last):
  File "setup.py", line 157, in <module>
    license="Simplified BSD License",
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/opt/python/3.7.1/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/python/3.7.1/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/python/3.7.1/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 230, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 180, in get_tag
    assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
AssertionError: would build wheel with unsupported tag ('cp35', 'abi3', 'linux_x86_64')
```
And on MacOS:
```
Traceback (most recent call last):
  File "setup.py", line 157, in <module>
    license="Simplified BSD License",
  File "/Users/travis/build/libtcod/python-tcod/venv/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/Users/travis/build/libtcod/python-tcod/venv/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 230, in run
    impl_tag, abi_tag, plat_tag = self.get_tag()
  File "/Users/travis/build/libtcod/python-tcod/venv/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 180, in get_tag
    assert tag in supported_tags, "would build wheel with unsupported tag {}".format(tag)
AssertionError: would build wheel with unsupported tag ('cp35', 'abi3', 'macosx_10_9_x86_64')
```

**Comment by agronholm** [comment]
The culprit seems to be commit b8b2800d3f2c87596ab0e21d330ab640e88c4434. Looks like the replacement for `imp.get_suffixes()` was not as compatible as advertised.

**Comment by agronholm** [comment]
Ah crap, no – it's a simple programming error. Line 147 should have been changed to `suffix` from `suffix[0]`.
