### ISSUE TITLE
 Wheel 0.34.0 broke installation from sdist: LookupError

### ISSUE THREAD

**Issue by marc1n** [pypa/wheel#333]
Checked on Python 2.7, 3.7 and pip 19.3, 20.0:
```
$ pip install -I --no-binary :all: 'wheel==0.34'
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting wheel==0.34
  Downloading wheel-0.34.0.tar.gz (60 kB)
     |████████████████████████████████| 60 kB 1.1 MB/s 
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/marcinr/env/test/bin/python /home/marcinr/env/test/local/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-KIkwz8/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 42' 'setuptools_scm[toml]>=3.4'
       cwd: None
  Complete output (41 lines):
  DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
  Collecting setuptools>=42
    Downloading setuptools-44.0.0.zip (858 kB)
  Collecting setuptools_scm[toml]>=3.4
    Downloading setuptools_scm-3.4.3.tar.gz (45 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'error'
    ERROR: Command errored out with exit status 2:
     command: /home/marcinr/env/test/bin/python /home/marcinr/env/test/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-dKsVJo/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=34.4' wheel
         cwd: None
    Complete output (28 lines):
    DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
    Collecting setuptools>=34.4
      Using cached setuptools-44.0.0.zip (858 kB)
    Collecting wheel
      Using cached wheel-0.34.0.tar.gz (60 kB)
    ERROR: Exception:
    Traceback (most recent call last):
      File "/home/marcinr/env/test/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
        status = self.run(options, args)
      File "/home/marcinr/env/test/lib/python2.7/site-packages/pip/_internal/commands/install.py", line 331, in run
        resolver.resolve(requirement_set)
      File "/home/marcinr/env/test/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
        discovered_reqs.extend(self._resolve_one(requirement_set, req))
      File "/home/marcinr/env/test/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
        abstract_dist = self._get_abstract_dist_for(req_to_install)
      File "/home/marcinr/env/test/lib/python2.7/site-packages/pip/_internal/legacy_resolve.py", line 282, in _get_abstract_dist_for
        abstract_dist = self.preparer.prepare_linked_requirement(req)
      File "/home/marcinr/env/test/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 516, in prepare_linked_requirement
        req, self.req_tracker, self.finder, self.build_isolation,
      File "/home/marcinr/env/test/lib/python2.7/site-packages/pip/_internal/operations/prepare.py", line 94, in _get_prepared_distribution
        with req_tracker.track(req):
      File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
        return self.gen.next()
      File "/home/marcinr/env/test/lib/python2.7/site-packages/pip/_internal/req/req_tracker.py", line 148, in track
        self.add(req)
      File "/home/marcinr/env/test/lib/python2.7/site-packages/pip/_internal/req/req_tracker.py", line 115, in add
        raise LookupError(message)
    LookupError: https://files.pythonhosted.org/packages/15/39/728ccb81172c73f14084948b2d4561d5e51649dcf4b21d1f207b7363b1d7/wheel-0.34.0.tar.gz#sha256=a69231973dccde8558f80f2ef058335a1d0bc1b55b2a5a2dfb5097e151e3c498 (from https://pypi.org/simple/wheel/) (requires-python:!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*,>=2.7) is already being built: wheel==0.34 from https://files.pythonhosted.org/packages/15/39/728ccb81172c73f14084948b2d4561d5e51649dcf4b21d1f207b7363b1d7/wheel-0.34.0.tar.gz#sha256=a69231973dccde8558f80f2ef058335a1d0bc1b55b2a5a2dfb5097e151e3c498
    ----------------------------------------
  ERROR: Command errored out with exit status 2: /home/marcinr/env/test/bin/python /home/marcinr/env/test/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-dKsVJo/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=34.4' wheel Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/marcinr/env/test/bin/python /home/marcinr/env/test/local/lib/python2.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-KIkwz8/overlay --no-warn-script-location --no-binary :all: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 42' 'setuptools_scm[toml]>=3.4' Check the logs for full command output.
```

**Comment by tomasmor42** [comment]
We are also experiencing this issue and is blocking us from deploying.

**Comment by Askir** [comment]
@tomasmor42 Just fix your wheel version to <0.34 for now. And use a package manager like pipenv or poetry to lock all your versions so you don't immediately get the newest realease for everything.

**Comment by jamadden** [comment]
Looks like a dup of #332 (which has a better error message).

**Comment by agronholm** [comment]
Closing as duplicate.
