### ISSUE TITLE
bdist_wheel setup that works for 3.5, 3.6 and 3.7 fails in 3.8

### ISSUE THREAD

**Issue by Helveg** [pypa/wheel#343]
The following setup that I use fails in 3.8:

``` python
#!/usr/bin/env python
from setuptools import setup
import rtree
import os

import itertools as it

try:
    from wheel.bdist_wheel import bdist_wheel as _bdist_wheel
    class bdist_wheel(_bdist_wheel):
        def finalize_options(self):
            _bdist_wheel.finalize_options(self)
            self.root_is_pure = False
except ImportError:
    bdist_wheel = None

# Get text from README.txt
with open('docs/source/README.txt', 'r') as fp:
    readme_text = fp.read()

extras_require = {
    'test': ['pytest>=3', 'pytest-cov', 'numpy']
}

extras_require['all'] = list(set(it.chain(*extras_require.values())))

setup(
    name          = 'Rtree',
    version       = rtree.__version__,
    description   = 'R-Tree spatial index for Python GIS',
    license       = 'MIT',
    keywords      = 'gis spatial index r-tree',
    author        = 'Sean Gillies',
    author_email  = 'sean.gillies@gmail.com',
    maintainer        = 'Howard Butler',
    maintainer_email  = 'howard@hobu.co',
    url   = 'https://github.com/Toblerity/rtree',
    long_description = readme_text,
    packages      = ['rtree'],
    include_package_data=True,
    package_data={"rtree": ["lib/*", "include/**/*", "include/**/**/*"]},
    install_requires = ['setuptools'],
    extras_require = extras_require,
    tests_require = extras_require['test'],
    zip_safe = False,
    classifiers   = [
      'Development Status :: 5 - Production/Stable',
      'Intended Audience :: Developers',
      'Intended Audience :: Science/Research',
      'License :: OSI Approved :: MIT License',
      'Operating System :: OS Independent',
      'Programming Language :: C',
      'Programming Language :: C++',
      'Programming Language :: Python',
      'Topic :: Scientific/Engineering :: GIS',
      'Topic :: Database',
      ],
    cmdclass={'bdist_wheel': bdist_wheel}
)
```

It generates the following error:

```
Traceback (most recent call last):
  File "setup.py", line 27, in <module>
    setup(
  File "/home/robin/.pyenv/versions/3.8.1/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/home/robin/.pyenv/versions/3.8.1/lib/python3.8/distutils/core.py", line 134, in setup
    ok = dist.parse_command_line()
  File "/home/robin/.pyenv/versions/3.8.1/lib/python3.8/site-packages/setuptools/dist.py", line 705, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/home/robin/.pyenv/versions/3.8.1/lib/python3.8/distutils/dist.py", line 483, in parse_command_line
    args = self._parse_command_opts(parser, args)
  File "/home/robin/.pyenv/versions/3.8.1/lib/python3.8/site-packages/setuptools/dist.py", line 1020, in _parse_command_opts
    nargs = _Distribution._parse_command_opts(self, parser, args)
  File "/home/robin/.pyenv/versions/3.8.1/lib/python3.8/distutils/dist.py", line 545, in _parse_command_opts
    if not issubclass(cmd_class, Command):
TypeError: issubclass() arg 1 must be a class
```

**Comment by Helveg** [comment]
It was because `wheel` wasn't installed in my pyenv :) It's what I get for copy pasting from StackOverflow :+1:
