### ISSUE TITLE
bdist_wheel regression for Python 2.7

### ISSUE THREAD

**Issue by AWSjswinney** [pypa/wheel#388]
A recent [change](https://github.com/pypa/wheel/pull/383/files#diff-968e9434803a49381f6dd3ced4131c331ae036ba3d1ff0273d9491cbada083adR389) introduced a regression in the `bdist_wheel` command for Python 2.7

Here is a stack trace:
```
Traceback (most recent call last):
  File "setup.py", line 75, in <module>
    setup_requires=setup_requires
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/site-packages/skbuild/setuptools_wrap.py", line 693, in setup
    return upstream_setup(*args, **kw)
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/site-packages/setuptools/__init__.py", line 162, in setup
    return distutils.core.setup(**attrs)
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/site-packages/skbuild/command/bdist_wheel.py", line 41, in run
    super(bdist_wheel, self).run(*args, **kwargs)
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 353, in run
    self.write_wheelfile(distinfo_dir)
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/site-packages/skbuild/command/bdist_wheel.py", line 78, in write_wheelfile
    super(bdist_wheel, self).write_wheelfile(wheelfile_base, generator)
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 393, in write_wheelfile
    BytesGenerator(buffer, maxheaderlen=0).flatten(msg)
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/Users/travis/.pyenv/versions/2.7.15/lib/python2.7/email/generator.py", line 145, in _write_headers
    print >> self._fp, v
TypeError: 'unicode' does not have the buffer interface
```

This is blocking Python 2.7 wheel builds for a recent [pull request](https://github.com/scikit-build/ninja-python-distributions/pull/40) to scikit-build/ninja-python-distributions. You can see output from the CI builds there where it fails on all Python 2.7 wheel builds on various platforms.

Thanks for reviewing!

**Comment by agronholm** [comment]
Odd that all the tests on 2.7 still passed. If you could help me figure out what went wrong, that would speed up the fix too.

**Comment by agronholm** [comment]
Scikit-build seems to be the culprit here. It changes the "Generator" header to unicode (`u'skbuild 0.11.1'´).

**Comment by AWSjswinney** [comment]
Thanks for the quick fix. It's working again!
