### ISSUE TITLE
wheel fails to build cyvcf2

### ISSUE THREAD

**Issue by alanwilter** [pypa/wheel#391]
I'm seeing a really awkward behaviour while installing `cyvcf2` package, which depends on several others including `numpy` and `openssl`

To reproduce the issue, using `docker`:
```bash
mkdir cytest
cd cytest
cat << EOF >| Dockerfile
FROM amazonlinux:latest
RUN yum update -y \\
    && yum install -y --setopt install_weak_deps=false \\
    bzip2-devel gcc libcurl-devel make openssl-devel python3 python3-devel \\
    xz-devel zlib-devel
EOF

docker build -t cytest .
docker run --rm --name cytest -it cytest bash
```

Now, inside `docker`, do:

```bash
pip3 install --upgrade pip
pip install --upgrade wheel
pip install cyvcf2

Collecting cyvcf2
  Downloading cyvcf2-0.30.1.tar.gz (1.2 MB)
     |████████████████████████████████| 1.2 MB 908 kB/s
Collecting click
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
     |████████████████████████████████| 82 kB 326 kB/s
Collecting coloredlogs
  Downloading coloredlogs-15.0-py2.py3-none-any.whl (45 kB)
     |████████████████████████████████| 45 kB 1.0 MB/s
Collecting humanfriendly>=9.1
  Downloading humanfriendly-9.1-py2.py3-none-any.whl (86 kB)
     |████████████████████████████████| 86 kB 3.2 MB/s
Collecting numpy
  Downloading numpy-1.19.4-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 1.7 MB/s
Building wheels for collected packages: cyvcf2
  Building wheel for cyvcf2 (setup.py) ... done
  Created wheel for cyvcf2: filename=cyvcf2-0.30.1-cp37-cp37m-linux_x86_64.whl size=3209364 sha256=96e38dd85a78fb2cf210330c2bde2981b5c0eeb6ed32ef6a6335472fea3ded4a
  Stored in directory: /root/.cache/pip/wheels/f6/97/f2/0bb064c8cb546e1891e1e9cc7ec7bbe47a29ea7079d7c22984
Successfully built cyvcf2
Installing collected packages: humanfriendly, numpy, coloredlogs, click, cyvcf2
Successfully installed click-7.1.2 coloredlogs-15.0 cyvcf2-0.30.1 humanfriendly-9.1 numpy-1.19.4
```

and then, to test installation:

```python
bash-4.2# python3 -c "import cyvcf2; print(cyvcf2.__version__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib64/python3.7/site-packages/cyvcf2/__init__.py", line 1, in <module>
    from .cyvcf2 import (VCF, Variant, Writer, r_ as r_unphased, par_relatedness,
  File "cyvcf2/cyvcf2.pyx", line 1, in init cyvcf2.cyvcf2
ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject
```
However, if I do force a reinstall (note: `--no-cache-dir` is critical here):
```python
bash-4.2# pip --no-cache-dir install cyvcf2 --force-reinstall
...
bash-4.2# python3 -c "import cyvcf2; print(cyvcf2.__version__)"
0.30.1
```
it works just fine but it's really awkward.

Now quit and start another docker session:
```bash
docker run --rm --name cytest -it cytest bash
pip3 install --upgrade pip
## pip install --upgrade wheel #NOTE: skip wheel
pip install cyvcf2
...
Using legacy 'setup.py install' for cyvcf2, since package 'wheel' is not installed.
Installing collected packages: humanfriendly, numpy, coloredlogs, click, cyvcf2
    Running setup.py install for cyvcf2 ... done
Successfully installed click-7.1.2 coloredlogs-15.0 cyvcf2-0.30.1 humanfriendly-9.1 numpy-1.19.4
```
Testing:
```python
bash-4.2# python3 -c "import cyvcf2; print(cyvcf2.__version__)"
0.30.1
```
worked fine.

So, there's something weird happening when using `wheel`, which I intended to to avoid legacy code but, alas, it's not working for this particular case.

**Comment by agronholm** [comment]
How is this wheel's fault though?

**Comment by alanwilter** [comment]
I don't know, I just find out that if I use `wheel` instead of legacy to install this particular package, then it fails. If you have an idea where should I ask for help I'm all ears.
I don't know how `wheel` works under the bonnet.

**Comment by pfmoore** [comment]
I'd suggest speaking to the cyvcf2 project.

**Comment by pfmoore** [comment]
It looks like cyvcf2 doesn't declare its build-time dependency on numpy in a `pyproject.toml` file. I don't know why that would result in the symptoms you're seeing, but I'd start by sorting that out. (It also doen't declare that it needs Cython to build).

I think you're probably seeing a consequence of pip using build isolation, which needs to know what to install into the build environment, and you haven't told it..

**Comment by agronholm** [comment]
They use some dubious old school tricks in their `setup.py`. Modernizing their packaging setup would likely fix such problems.

**Comment by alanwilter** [comment]
Interesting, thanks, now I have something to investigate.
