### ISSUE TITLE
Not able to install dlib for python3.9.5

### ISSUE THREAD

**Issue by Goutham-source** [pypa/wheel#409]
pip3 install dlib
Collecting dlib
  Using cached dlib-19.22.0.tar.gz (7.4 MB)
Building wheels for collected packages: dlib
  Building wheel for dlib (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\iobrainl6\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\setup.py'"'"'; __file__='"'"'C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\iObrainL6\AppData\Local\Temp\pip-wheel-cjhrj9q9'
       cwd: C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\
  Complete output (58 lines):
  running bdist_wheel
  running build
  running build_py
  package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
  running build_ext
  Building extension for Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
  Invoking CMake setup: 'cmake C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\build\lib.win-amd64-3.9 -DPYTHON_EXECUTABLE=c:\users\iobrainl6\appdata\local\programs\python\python39\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\build\lib.win-amd64-3.9 -A x64'
  -- Building for: NMake Makefiles
  CMake Error at CMakeLists.txt:5 (message):

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    You must use Visual Studio to build a python extension on windows.  If you
    are getting this error it means you have not installed Visual C++.  Note
    that there are many flavors of Visual Studio, like Visual Studio for C#
    development.  You need to install Visual Studio for C++.

    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

  -- Configuring incomplete, errors occurred!
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\setup.py", line 222, in <module>
      setup(
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\setup.py", line 134, in run
      self.build_extension(ext)
    File "C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\setup.py", line 171, in build_extension
      subprocess.check_call(cmake_setup, cwd=build_folder)
    File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=c:\\users\\iobrainl6\\appdata\\local\\programs\\python\\python39\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\build\\lib.win-amd64-3.9', '-A', 'x64']' returned non-zero exit status 1.
  ----------------------------------------
  ERROR: Failed building wheel for dlib
  Running setup.py clean for dlib
Failed to build dlib
Installing collected packages: dlib
    Running setup.py install for dlib ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\iobrainl6\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\setup.py'"'"'; __file__='"'"'C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\iObrainL6\AppData\Local\Temp\pip-record-_929rgbk\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\iobrainl6\appdata\local\programs\python\python39\Include\dlib'
         cwd: C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\
    Complete output (60 lines):
    running install
    running build
    running build_py
    package init file 'tools\python\dlib\__init__.py' not found (or not a regular file)
    running build_ext
    Building extension for Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
    Invoking CMake setup: 'cmake C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\tools\python -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\build\lib.win-amd64-3.9 -DPYTHON_EXECUTABLE=c:\users\iobrainl6\appdata\local\programs\python\python39\python.exe -DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\build\lib.win-amd64-3.9 -A x64'
    -- Building for: NMake Makefiles
    CMake Error at CMakeLists.txt:5 (message):

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

      You must use Visual Studio to build a python extension on windows.  If you
      are getting this error it means you have not installed Visual C++.  Note
      that there are many flavors of Visual Studio, like Visual Studio for C#
      development.  You need to install Visual Studio for C++.

      !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

    -- Configuring incomplete, errors occurred!
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\setup.py", line 222, in <module>
        setup(
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\setup.py", line 134, in run
        self.build_extension(ext)
      File "C:\Users\iObrainL6\AppData\Local\Temp\pip-install-1tf5o7r0\dlib_3d7de33cdc2a44db85d1eac3fe161a22\setup.py", line 171, in build_extension
        subprocess.check_call(cmake_setup, cwd=build_folder)
      File "c:\users\iobrainl6\appdata\local\programs\python\python39\lib\subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', 'C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\tools\\python', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\build\\lib.win-amd64-3.9', '-DPYTHON_EXECUTABLE=c:\\users\\iobrainl6\\appdata\\local\\programs\\python\\python39\\python.exe', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE=C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\build\\lib.win-amd64-3.9', '-A', 'x64']' returned non-zero exit status 1.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\iobrainl6\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\setup.py'"'"'; __file__='"'"'C:\\Users\\iObrainL6\\AppData\\Local\\Temp\\pip-install-1tf5o7r0\\dlib_3d7de33cdc2a44db85d1eac3fe161a22\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\iObrainL6\AppData\Local\Temp\pip-record-_929rgbk\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\iobrainl6\appdata\local\programs\python\python39\Include\dlib' Check the logs for full command output.

**Comment by agronholm** [comment]
This is not a problem with wheel. Wheel does not handle the compilation of C extensions.

**Comment by Goutham-source** [comment]
Then what is the solution for this any idea that how can i install dlib
please help me through this

Regards,
Goutham K
Technical Trainer
iObrain Innovative Labz <http://www.iobrain.in>
Address: #786/A, 1st Floor, 1st Cross, 7th Block, 2nd Phase, Banashankari
3rd Stage, Bengaluru, Karnataka 560085


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by agronholm** [comment]
This is an issue tracker for the wheel project, not a general forum for asking for tech support. That said, the error message suggests that you do not have Visual Studio installed which is required to compile C extensions. [This page](https://wiki.python.org/moin/WindowsCompilers) may help you. If you need further help, ask on StackOverflow or on the `#python` channel on Libera IRC.
