### ISSUE TITLE
Building Wheel wheel on MacOS 13.3 fails under Homebrew

### ISSUE THREAD

**Issue by NeilBetham** [pypa/wheel#525]
Hello, I'm currently trying to install python 3.11 via Homebrew on MacOS 13.3 and it seems that something has changed since 13.2 which has broken Wheel. I tested with another machine on the previous OS release, 13.2, and did not see this issue. I tested the build using Homebrew's default wheel version of 0.38.4 and the latest release of 0.40.0. Both failed with different errors. I also tested with a fresh Homebrew prefix and still encountered the issue. For reference [this](https://github.com/Homebrew/homebrew-core/blob/dfae1476675f7dac6900b6ad05b40b1d8d3c8e7e/Formula/python@3.11.rb#L284) is the section of the Homebrew build script that is failing. I've also tested the other formulae for 3.10 and 3.9 and they all fail to build at this point with varying errors. I'm not convinced this is fully a Wheel problem but I don't know where to focus on next to debug the issue.

#### Python 3.11 - Wheel 0.38.4 Build Log
```
2023-04-02 00:12:05 +0000

/private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/bin/pip3
wheel
-v
--no-deps
--no-binary
:all:
--no-index
--no-build-isolation
--wheel-dir=/Users/<user>/.brew/Cellar/python@3.11/3.11.2_1/libexec
.

DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Processing /private/tmp/pythonA3.11--wheel-20230402-63660-qbuv34/wheel-0.38.4
  Preparing metadata (setup.py): started
  Running command python setup.py egg_info
  running egg_info
  creating /private/tmp/pip-pip-egg-info-4sjvsxe4/wheel.egg-info
  writing /private/tmp/pip-pip-egg-info-4sjvsxe4/wheel.egg-info/PKG-INFO
  writing dependency_links to /private/tmp/pip-pip-egg-info-4sjvsxe4/wheel.egg-info/dependency_links.txt
  writing entry points to /private/tmp/pip-pip-egg-info-4sjvsxe4/wheel.egg-info/entry_points.txt
  writing requirements to /private/tmp/pip-pip-egg-info-4sjvsxe4/wheel.egg-info/requires.txt
  writing top-level names to /private/tmp/pip-pip-egg-info-4sjvsxe4/wheel.egg-info/top_level.txt
  writing manifest file '/private/tmp/pip-pip-egg-info-4sjvsxe4/wheel.egg-info/SOURCES.txt'
  reading manifest file '/private/tmp/pip-pip-egg-info-4sjvsxe4/wheel.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.dynlib' under directory 'tests'
  no previously-included directories found matching 'tests/testdata/*/build'
  no previously-included directories found matching 'tests/testdata/*/dist'
  no previously-included directories found matching 'tests/testdata/*/*.egg-info'
  adding license file 'LICENSE.txt'
  writing manifest file '/private/tmp/pip-pip-egg-info-4sjvsxe4/wheel.egg-info/SOURCES.txt'
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: wheel
  Building wheel for wheel (setup.py): started
  Running command python setup.py bdist_wheel
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "/private/tmp/pythonA3.11--wheel-20230402-63660-qbuv34/wheel-0.38.4/setup.py", line 5, in <module>
      setup()
    File "/private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 172, in setup
      ok = dist.parse_command_line()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 474, in parse_command_line
      args = self._parse_command_opts(parser, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/dist.py", line 1107, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 533, in _parse_command_opts
      cmd_class = self.get_command_class(command)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/lib/python3.11/site-packages/setuptools/dist.py", line 954, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
                                          ^^^^^^^^^
    File "/Users/<user>/.brew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
      module = import_module(match.group('module'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/<user>/.brew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 940, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 28, in <module>
      from .macosx_libfile import calculate_macosx_platform_tag
    File "/private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/lib/python3.11/site-packages/wheel/macosx_libfile.py", line 43, in <module>
      import ctypes
    File "/Users/<user>/.brew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /private/tmp/pythonA3.11-20230401-63660-1toasz8/Python-3.11.2/whl_build/bin/python3.11 -u -c '
  exec(compile('"'"''"'"''"'"'
  # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
  #
  # - It imports setuptools before invoking setup.py, to enable projects that directly
  #   import from `distutils.core` to work with newer packaging standards.
  # - It provides a clear error message when setuptools is not installed.
  # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
  #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
  #     manifest_maker: standard file '"'"'-c'"'"' not found".
  # - It generates a shim setup.py, for handling setup.cfg-only projects.
  import os, sys, tokenize

  try:
      import setuptools
  except ImportError as error:
      print(
          "ERROR: Can not execute `setup.py` since setuptools is not available in "
          "the build environment.",
          file=sys.stderr,
      )
      sys.exit(1)

  __file__ = %r
  sys.argv[0] = __file__

  if os.path.exists(__file__):
      filename = __file__
      with tokenize.open(__file__) as f:
          setup_py_code = f.read()
  else:
      filename = "<auto-generated setuptools caller>"
      setup_py_code = "from setuptools import setup; setup()"

  exec(compile(setup_py_code, filename, "exec"))
  '"'"''"'"''"'"' % ('"'"'/private/tmp/pythonA3.11--wheel-20230402-63660-qbuv34/wheel-0.38.4/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' bdist_wheel -d /private/tmp/pip-wheel-jebaw8x3
  cwd: /private/tmp/pythonA3.11--wheel-20230402-63660-qbuv34/wheel-0.38.4/
  Building wheel for wheel (setup.py): finished with status 'error'
  ERROR: Failed building wheel for wheel
  Running setup.py clean for wheel
  Running command python setup.py clean
  running clean
  removing 'build/lib' (and everything under it)
  'build/bdist.macosx-13-arm64' does not exist -- can't clean it
  'build/scripts-3.11' does not exist -- can't clean it
  removing 'build'
Failed to build wheel
ERROR: Failed to build one or more wheels

HOMEBREW_VERSION: 4.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: cf6614b50eac1c9f4bf386dc6989f0d443148df8
Last commit: 5 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7af1220d7f32bab829b15485648d0ef3ff4f8976
Core tap last commit: 55 minutes ago
Core tap branch: master
Core tap JSON: 01 Apr 23:29 UTC
HOMEBREW_PREFIX: /Users/<user>/.brew
HOMEBREW_REPOSITORY: /Users/<user>/.brew
HOMEBREW_CELLAR: /Users/<user>/.brew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_BOOTSNAP: set
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j10
CMAKE_PREFIX_PATH: /Users/<user>/.brew/opt/openssl@1.1:/Users/<user>/.brew/opt/readline:/Users/<user>/.brew/opt/sqlite:/Users/<user>/.brew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /Users/<user>/.brew/opt/openssl@1.1/lib/pkgconfig:/Users/<user>/.brew/opt/readline/lib/pkgconfig:/Users/<user>/.brew/opt/sqlite/lib/pkgconfig:/Users/<user>/.brew/opt/xz/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/Users/<user>/.brew/Library/Homebrew/os/mac/pkgconfig/13
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
ACLOCAL_PATH: /Users/<user>/.brew/share/aclocal
PATH: /Users/<user>/.brew/Library/Homebrew/shims/mac/super:/Users/<user>/.brew/opt/pkg-config/bin:/Users/<user>/.brew/opt/openssl@1.1/bin:/Users/<user>/.brew/opt/sqlite/bin:/Users/<user>/.brew/opt/xz/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

#### Python 3.11 - Wheel 0.40.0 Build Log
```
2023-04-01 23:46:36 +0000

/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/bin/pip3
install
-v
--no-deps
--no-binary
:all:
--no-index
--no-build-isolation
.

Using pip 22.3.1 from /private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip (python 3.11)
DEPRECATION: --no-binary currently disables reading from the cache of locally built wheels. In the future --no-binary will not influence the wheel cache. pip 23.1 will enforce this behaviour change. A possible replacement is to use the --no-cache-dir option. You can use the flag --use-feature=no-binary-enable-wheel-cache to test the upcoming behaviour. Discussion can be found at https://github.com/pypa/pip/issues/11453
Processing /private/tmp/pythonA3.11--wheel-20230401-29818-adblmk/wheel-0.40.0
  Preparing metadata (pyproject.toml): started
  Running command Preparing metadata (pyproject.toml)
  Preparing metadata (pyproject.toml): finished with status 'done'
ERROR: Exception:
Traceback (most recent call last):
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 400, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 577, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 69, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/distributions/sdist.py", line 61, in prepare_distribution_metadata
    self.req.prepare_metadata()
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/req/req_install.py", line 535, in prepare_metadata
    self.metadata_directory = generate_metadata(
                              ^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/operations/build/metadata.py", line 35, in generate_metadata
    distinfo_dir = backend.prepare_metadata_for_build_wheel(metadata_dir)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 706, in prepare_metadata_for_build_wheel
    return super().prepare_metadata_for_build_wheel(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_vendor/pep517/wrappers.py", line 189, in prepare_metadata_for_build_wheel
    return self._call_hook('prepare_metadata_for_build_wheel', {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_vendor/pep517/wrappers.py", line 319, in _call_hook
    raise BackendUnavailable(data.get('traceback', ''))
pip._vendor.pep517.wrappers.BackendUnavailable: Traceback (most recent call last):
  File "/private/tmp/pythonA3.11-20230401-29818-1ri3rrq/Python-3.11.2/whl_build/lib/python3.11/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 77, in _build_backend
    obj = import_module(mod_path)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/<user>/.brew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'flit_core'


HOMEBREW_VERSION: 4.0.10
ORIGIN: https://github.com/Homebrew/brew
HEAD: cf6614b50eac1c9f4bf386dc6989f0d443148df8
Last commit: 5 days ago
Core tap origin: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7af1220d7f32bab829b15485648d0ef3ff4f8976
Core tap last commit: 30 minutes ago
Core tap branch: master
Core tap JSON: 01 Apr 23:29 UTC
HOMEBREW_PREFIX: /Users/<user>/.brew
HOMEBREW_REPOSITORY: /Users/<user>/.brew
HOMEBREW_CELLAR: /Users/<user>/.brew/Cellar
HOMEBREW_CASK_OPTS: []
HOMEBREW_MAKE_JOBS: 10
HOMEBREW_NO_AUTO_UPDATE: set
HOMEBREW_NO_BOOTSNAP: set
HOMEBREW_NO_INSTALL_FROM_API: set
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: 10-core 64-bit arm_firestorm_icestorm
Clang: 14.0.3 build 1403
Git: 2.39.2 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Curl: 7.87.0 => /usr/bin/curl
macOS: 13.3-arm64
CLT: 14.3.0.0.1.1679647830
Xcode: 14.3
Rosetta 2: false

HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j10
CMAKE_PREFIX_PATH: /Users/<user>/.brew/opt/openssl@1.1:/Users/<user>/.brew/opt/readline:/Users/<user>/.brew/opt/sqlite:/Users/<user>/.brew
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
PKG_CONFIG_PATH: /Users/<user>/.brew/opt/openssl@1.1/lib/pkgconfig:/Users/<user>/.brew/opt/readline/lib/pkgconfig:/Users/<user>/.brew/opt/sqlite/lib/pkgconfig:/Users/<user>/.brew/opt/xz/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/Users/<user>/.brew/Library/Homebrew/os/mac/pkgconfig/13
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX13.sdk
ACLOCAL_PATH: /Users/<user>/.brew/share/aclocal
PATH: /Users/<user>/.brew/Library/Homebrew/shims/mac/super:/Users/<user>/.brew/opt/pkg-config/bin:/Users/<user>/.brew/opt/openssl@1.1/bin:/Users/<user>/.brew/opt/sqlite/bin:/Users/<user>/.brew/opt/xz/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

**Comment by henryiii** [comment]
Isolated builds are or were broken in homebrew (first saw it about 6 months ago?). They patch Python which breaks the isolated environments for building packages. If you make a venv, or use build via pipx, or use non-isolated builds, it’s fine, but the base environment is broken.

I don’t know if it was fixed (haven’t seen many complaints since the initial batch), and then returned in the latest macOS, or of it’s just different versions of brew things between the two.

**Comment by NeilBetham** [comment]
Okay, I will close this and raise the issue over in Homebrew. Thanks for the info.
