### ISSUE TITLE
pip install vrcpy does not work after setuptools upgrading version to 72.0.0

### ISSUE THREAD

**Issue by marcoscunha** [pypa/wheel#629]
Using pip install vcrpy does not work with new version of setuptools 72.0.0. 

During pip installation, the requirements are not fixed to a specific version of setuptools. It provokes an error for new installation. 

It appears after 28 July, after setuptools new release (see here:  https://setuptools.pypa.io/en/latest/history.html) 

Command Line : 
```
pip install --force-reinstall --upgrade vcrpy==6.0.1 --no-cache                                                                                                                            
```

Output: 
```
Collecting vcrpy==6.0.1
  Downloading vcrpy-6.0.1.tar.gz (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.8/84.8 kB 5.0 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/home/mcunha/devel/Voltyo/src/aegilim/core-architecture/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/mcunha/devel/Voltyo/src/aegilim/core-architecture/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mcunha/devel/Voltyo/src/aegilim/core-architecture/.venv/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-pf0f63fq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 327, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=[])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-pf0f63fq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 297, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-pf0f63fq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 497, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-pf0f63fq/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 313, in run_setup
          exec(code, locals())
        File "<string>", line 9, in <module>
      ModuleNotFoundError: No module named 'setuptools.command.test'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by agronholm** [comment]
Why are you reporting this as a wheel bug? Since setuptools 71, it no longer uses `wheel` in any capacity.

**Comment by marcoscunha** [comment]
Indeed you are right that is wheel that brokes the chain of installation.
  
I report this here because the vcrpy's chain of installation is broken.

Do you think something could be done to avoid this in the future ?

**Comment by marcoscunha** [comment]
you are right!!!

 I will move this issue to vcrpy repo! 

Thanks !

**Comment by agronholm** [comment]
I don't think you understood anything I just said. Wheel is NOT part of the chain of installation! Wheel has nothing whatsoever to do with vcrpy, so please don't report issues with it here.

**Comment by marcoscunha** [comment]
Sorry, I send this issue too fast in the wrong repo. ! 

Thanks for you answer !
