### ISSUE TITLE
Broken compatibility with python-keyring >= 3.0

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#85]
Originally reported by: **Pierre Jaury (Bitbucket: [kaiyou](https://bitbucket.org/kaiyou), GitHub: [kaiyou](https://github.com/kaiyou))**

----------------------------------------

Since keyring 3.0, backward compatibility references to legacy backend names have been removed. Thus, wheel is broken when trying to import directly from keyring.backend. Especially:

```
#!python

Traceback (most recent call last):
  File "/usr/bin/wheel", line 9, in <module>
    load_entry_point('wheel==0.22.0', 'console_scripts', 'wheel')()
  File "/usr/lib64/python2.7/site-packages/wheel/tool/__init__.py", line 358, in main
    args.func(args)
  File "/usr/lib64/python2.7/site-packages/wheel/tool/__init__.py", line 269, in keygen_f
    keygen()
  File "/usr/lib64/python2.7/site-packages/wheel/tool/__init__.py", line 50, in keygen
    if isinstance(kr, keyring.backend.BasicFileKeyring):
AttributeError: 'module' object has no attribute 'BasicFileKeyring
```

keyring.backend submodules have been out there since keyring 1.1, I think it is safe to reference these modules instead of legacy references. Another option would be to reference keyring <= 3.0 as a dependency.

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/85

**Comment by agronholm** [comment]
There is no `BasicFileKeyring` in the source code so I'm closing this issue as obsolete.
