### ISSUE TITLE
"wheel verify" crashes

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#94]
Originally reported by: **Ralf Gommers (Bitbucket: [ralfgommers](https://bitbucket.org/ralfgommers), GitHub: Unknown)**

----------------------------------------

``RECORD`` exists (which is according to PEP 427), ``RECORD.jws`` does not.

    $ wheel verify numpy-1.9.0.dev_3aa76ba-cp27-none-linux_i686.whl 
    Traceback (most recent call last):
      File "/home/rgommers/.local/bin/wheel", line 9, in <module>
        load_entry_point('wheel==0.22.0', 'console_scripts', 'wheel')()
      File "/home/rgommers/.local/lib/python2.7/site-packages/wheel/tool/__init__.py", line 358, in main
        args.func(args)
      File "/home/rgommers/.local/lib/python2.7/site-packages/wheel/tool/__init__.py", line 286, in verify_f
        verify(args.wheelfile)
      File "/home/rgommers/.local/lib/python2.7/site-packages/wheel/tool/__init__.py", line 119, in verify
        sig = json.loads(native(wf.zipfile.open(sig_name).read()))
      File "/home/rgommers/.local/lib/python2.7/site-packages/wheel/install.py", line 437, in open
        ef = zipfile.ZipFile.open(self, name_or_info, mode, pwd)
      File "/usr/lib/python2.7/zipfile.py", line 957, in open
        zinfo = self.getinfo(name)
      File "/usr/lib/python2.7/zipfile.py", line 905, in getinfo
        'There is no item named %r in the archive' % name)
    KeyError: "There is no item named 'numpy-1.9.0.dev_3aa76ba.dist-info/RECORD.jws' in the archive"

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/94

**Comment by agronholm** [comment]
Not sure what you expected to happen when the wheel wasn't signed in the first place, but I added a better error message for this now.
