### ISSUE TITLE
ImportError: No module named dirspec.basedir

### ISSUE THREAD

**Issue by agronholm** [pypa/wheel#95]
Originally reported by: **Anonymous**

----------------------------------------

Got the following error when using in a virtualenv

wheel keygen
Traceback (most recent call last):
  File "/usr/local/bin/wheel", line 9, in <module>
    load_entry_point('wheel==0.22.0', 'console_scripts', 'wheel')()
  File "/usr/local/lib/python2.7/site-packages/wheel/tool/__init__.py", line 358, in main
    args.func(args)
  File "/usr/local/lib/python2.7/site-packages/wheel/tool/__init__.py", line 269, in keygen_f
    keygen()
  File "/usr/local/lib/python2.7/site-packages/wheel/tool/__init__.py", line 42, in keygen
    wk = WheelKeys().load()
  File "/usr/local/lib/python2.7/site-packages/wheel/signatures/keys.py", line 47, in load
    for path in load_config_paths('wheel'):
  File "/usr/local/lib/python2.7/site-packages/wheel/util.py", line 124, in load_config_paths
    import dirspec.basedir
ImportError: No module named dirspec.basedir

----------------------------------------
- Bitbucket: https://bitbucket.org/pypa/wheel/issue/95

**Comment by agronholm** [comment]
The codebase does not contain the word `dirspec` in the code any more so this issue seems obsolete. Also the other mentioned issue has been closed, so I'm closing this one too.
